### PR TITLE
Fixed routing / base of app at GitHub Pages

### LINKED ISSUE #29: Fix routing / base of React app at GitHub Pages
This React app is deployed to https://digia.online/react-foundation-docs/

But there's a 404 loading the app:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Foundation as React components">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>React + Foundation · Foundation as React components</title>
</head>
<body>
<div id="root"></div>
<script type="text/javascript" src="/app.7b5695e2abaf01cd6a5b.js"></script></body>
</html>
```

That's because it's trying to load the app at 

* https://digia.online/app.7b5695e2abaf01cd6a5b.js

When it's really at:

* https://digia.online/react-foundation-docs/app.7b5695e2abaf01cd6a5b.js

It needs fixing so everything loads properly.

### PR DESCRIPTION
**Pull request by supanthapaul**
Fixes #29 
The fix needed changes in the **publicPath** property of webpack config as the app is served under a sub-directory. All the changed files are commented, if you find any issue or have some doubts, let me know 😃

### CODE REVIEW

File: webpack/production.js [hunk 1]
```diff
@@ -8,4 +9,4 @@ module.exports = Object.assign({}, {
       template: 'src/main.html'
     }),
   ]
-}, require('./config'));
+}, getConfig("react-foundation-docs/"));	// sets the public path to be under '/react-foundation-docs/' for production
```
Comment (hugovk) [inline webpack/production.js:12]: Consistent quotes:
```suggestion
}, getConfig('react-foundation-docs/'));  // sets the public path to be under '/react-foundation-docs/' for production
```

File: webpack/development.js [hunk 2]
```diff
@@ -10,4 +11,4 @@ module.exports = Object.assign({}, {
     }),
     new webpack.HotModuleReplacementPlugin(),
   ]
-}, require('./config'));
+}, getConfig());	// gets the config with default public path ('/')
```
Comment (hugovk) [inline webpack/development.js:14]:
```suggestion
}, getConfig());  // gets the config with default public path ('/')
```

File: webpack/config.js [hunk 3]
```diff
@@ -1,13 +1,17 @@
 var path = require('path');
 
-module.exports = {
+module.exports = (publicPath = "/") => ({
   entry: {
-    app: path.resolve(__dirname, '../src/main.js')
+		app: path.resolve(__dirname, '../src/main.js'),
+		// this creates a duplicate output bundle for local serving as the app expects output bundle to be in the 'react-foundation-docs/' sub-directory
```
Comment (hugovk) [inline webpack/config.js:6]: Consistent spaces instead of tabs:
```suggestion
    app: path.resolve(__dirname, '../src/main.js'),
    // this creates a duplicate output bundle for local serving as the app expects output bundle to be in the 'react-foundation-docs/' sub-directory
```

File: webpack/config.js [hunk 4]
```diff
@@ -1,13 +1,17 @@
...
+		// You can comment it out to push it to Github Pages, this is purely for the local serving of the dist directory
+		'react-foundation-docs/app': path.resolve(__dirname, '../src/main.js'),
```
Comment (hugovk) [inline webpack/config.js:8]:
```suggestion
    'react-foundation-docs/app': path.resolve(__dirname, '../src/main.js'),
```

File: webpack/config.js [hunk 5]
```diff
@@ -1,13 +1,17 @@
...
   },
   output: {
     path: path.resolve(__dirname, '../dist'),
-    filename: '[name].[hash].js',
-    publicPath: '/',
+		filename: '[name].[hash].js',
+		// sets the output public path to be under the publicPath passed
```
Comment (hugovk) [inline webpack/config.js:13]:
```suggestion
    filename: '[name].[hash].js',
    // sets the output public path to be under the publicPath passed
```

**Review by hugovk — CHANGES_REQUESTED** [review]
Thanks for this!

Just some little nits to suggest.

**Comment by hugovk** [comment]
Testing this with: `rm -rf dist && npm run dist && npm run serve`

I can then visit http://localhost:5000/ and the site loads, but I only see a directory listing of the app.js at http://localhost:5000/react-foundation-docs

Will that mean the deployed site also won't load?

**Comment by supanthapaul** [comment]
@hugovk I've committed the changes you've requested, have a look!

**Comment by hugovk** [comment]
> Testing this with: `rm -rf dist && npm run dist && npm run serve`
> 
> I can then visit [http://localhost:5000](http://localhost:5000/) and the site loads, but I only see a directory listing of the app.js at http://localhost:5000/react-foundation-docs
> 
> Will that mean the deployed site also won't load?

I deployed to my fork and it doesn't load:

https://hugovk.github.io/react-foundation-docs/

**Comment by supanthapaul** [comment]
> > Testing this with: `rm -rf dist && npm run dist && npm run serve`
> > I can then visit [http://localhost:5000](http://localhost:5000/) and the site loads, but I only see a directory listing of the app.js at http://localhost:5000/react-foundation-docs
> > Will that mean the deployed site also won't load?
> 
> I deployed to my fork and it doesn't load:
> 
> https://hugovk.github.io/react-foundation-docs/

That was happening because the App component renders NotFound component when not on the root directory. I've pushed the necessary changed to allow for the sub-directories. Have a look 😁

**Comment by supanthapaul** [comment]
The deployed site should load just fine now, let me know!

**Comment by hugovk** [comment]
There's now two app.js files and both are 404:

```html
<script type="text/javascript" src="react-foundation-docs/app.d73cbd2c3e02d7e5ce3f.js"></script>
<script type="text/javascript" src="react-foundation-docs/react-foundation-docs/app.d73cbd2c3e02d7e5ce3f.js"></script></body>
```

https://hugovk.github.io/react-foundation-docs/

**Comment by supanthapaul** [comment]
> There's now two app.js files and both are 404:
> 
> ```
> <script type="text/javascript" src="react-foundation-docs/app.d73cbd2c3e02d7e5ce3f.js"></script>
> <script type="text/javascript" src="react-foundation-docs/react-foundation-docs/app.d73cbd2c3e02d7e5ce3f.js"></script></body>
> ```
> 
> https://hugovk.github.io/react-foundation-docs/

That is happening because of the duplicate bundle created for making the local serving work. You can remove the line and the production build on deployment should still work.
image

**Comment by hugovk** [comment]
Please can you update the PR so it works on local and deployment? The idea of auto-deployment is not to need to make any manual changes first :)

**Comment by supanthapaul** [comment]
> Please can you update the PR so it works on local and deployment? The idea of auto-deployment is not to need to make any manual changes first :)

It does work on local and deployment. If I remove the duplicate bundle the local react server(through npm start) and Github Pages both will work. But the 'serve' won't work as the production build expects a sub-directory. Do you want me to remove the duplicate output bundle?

**Comment by hugovk** [comment]
I checked again and it's now working at https://hugovk.github.io/react-foundation-docs/, I guess it was a caching issue. Sorry about that!

And thank you! Let's merge!

**Review by hugovk — APPROVED** [review]

**Comment by supanthapaul** [comment]
> I checked again and it's now working at https://hugovk.github.io/react-foundation-docs/, I guess it was a caching issue. Sorry about that!
> 
> And thank you! Let's merge!

Thank you for the merge! If you can, please review the PR on hacktoberfest :)

**Comment by hugovk** [comment]
It should show up for you at https://hacktoberfest.digitalocean.com/profile soon.

Also confirmed it's now deployed fine to https://digia.online/react-foundation-docs/

Thanks again!

**Comment by supanthapaul** [comment]
> It should show up for you at https://hacktoberfest.digitalocean.com/profile soon.
> 
> Also confirmed it's now deployed fine to https://digia.online/react-foundation-docs/
> 
> Thanks again!

It looks great, happy to help! If you'd like to connect with me I'm [@supanthapaul](https://twitter.com/supanthapaul) on Twitter 😄
